### ISSUE TITLE
Redirect Ceton UI, Visible in fHDHR

### ISSUE THREAD

**Issue by arrmo** [fHDHR/fHDHR_plugin_origin_ceton#18]
Just a thought, but this would be handy - in one place, and available outside the server machine.

Thoughts?

**Comment by deathbybandaid** [comment]
Sounds like something nginx reverse proxy would be better suited for tbh

**Comment by arrmo** [comment]
Doh! And yes, have it working here now 🤣. Thanks!

But ... that's as a separate page, was thinking it would be nice to show that within fHDHR - agreed? If so, we just need to figure out how to proxy through a web page (poor wording there I think, but hopefully you get my point).

**Comment by arrmo** [comment]
Seems like Flash supports Proxy - is it just a matter of setting this up (as a proxy)? Sorry, not very familiar (yet 😆) with Flask.
https://medium.com/customorchestrator/simple-reverse-proxy-server-using-flask-936087ce0afb

Thanks!

**Comment by arrmo** [comment]
Thinking we can close this one now - with the info added to the Ceton tuner page. Agreed?

Thanks!
