### ISSUE TITLE
Set Ceton Tuner Count Based on UI

### ISSUE THREAD

**Issue by arrmo** [fHDHR/fHDHR_plugin_origin_ceton#19]
A thought, but ... use the UI to determine (and set) the number of tuners - rather than a parameter in config.ini?

Thanks!

**Comment by deathbybandaid** [comment]
The tuner system is part of core. And there is a settings page in the web interface to change the config.

plugins are able to override the default tuner amount with different logic though

**Comment by arrmo** [comment]
Agreed! Sorry, that's what I was trying to say. For Ceton (specifically), report the number of tuners (for it), based on detection ... agreed?

Thanks!

**Comment by DanAustinGH** [comment]
A couple other projects I looked at found the tuner count detection to be unreliable, so I went straight to static.  If you want to add it and it works consistently, I have no objections.

**Comment by deathbybandaid** [comment]
We also want to make certain the config value has the final say thpugh

**Comment by arrmo** [comment]
@DanAustinGH I may have an answer, delivered by the Ceton UI itself 😆. But to confirm ... do you have a 4 or 6 tuner card? I have 4, but I want to also check this with 6, to make sure.

@deathbybandaid Do you mean - read it if possible (and reliable!), but still have the ability to override? If so - yes, agreed.

**Comment by arrmo** [comment]
@DanAustinGH Can you let me know what you see at http://192.168.200.1/Instance.css? I get this,
```
.tab_Five { display: none; }
.tab_Six { display: none; }
.tab_Nine { display: none; }
```

Yep, it makes sense - for a 4 tuner card, tabs 5 and 6 are disabled (not displayed). And this comes directly from the Ceton UI.

Thanks!

**Comment by DanAustinGH** [comment]
I cannot open the css directly.  I have the stand-alone 6 tuner and do have tabs five and six

**Comment by arrmo** [comment]
> I cannot open the css directly. I have the stand-alone 6 tuner and do have tabs five and six

Hmmm ... so the file doesn't even exist, even if the Browser DevTools?

Thanks!

**Comment by DanAustinGH** [comment]
Chrome does not throw any errors, but the devtool does not show any contents in the file

**Comment by arrmo** [comment]
OK, gotcha. Is this the trigger then? In my case, 4 tuners => I can clearly see that Ceton disables pages (tuners) 5 and 6.

Thanks!

**Comment by arrmo** [comment]
I may have an answer - I hope 😜. I wrote some code (attached to this post, ssdp borrowed from [here](https://gist.github.com/dankrause/6000248)!) => it runs ssdp, then gets the discovery.xml information, finally parsing it. I have attached the code - give it a try on your side as well?

The output from the code for me is,
```
Device Friendly Name:  Ceton InfiniTV PCIe (00-80-30-0b) Tuner 1
Device Friendly Name:  Ceton InfiniTV PCIe (00-80-30-0b) Tuner 2
Device Friendly Name:  Ceton InfiniTV PCIe (00-80-30-0b) Tuner 3
Device Friendly Name:  Ceton InfiniTV PCIe (00-80-30-0b) Tuner 4
Device Friendly Name:  Ceton InfiniTV (00-80-30-0b), OCTA 1
Device Friendly Name:  Ceton InfiniTV (00-80-30-0b), OCTA 2
```
[ssdpCeton.zip](https://github.com/fHDHR/fHDHR_plugin_origin_ceton/files/8020497/ssdpCeton.zip)

Thoughts?

Thanks!

**Comment by DanAustinGH** [comment]
It grumbles about not being able to bind/assign the IP set in ssdpCeton.py
I tried the IP of the Ceton, of the host I was running the tool on and a random IP in the network range.

**Comment by DanAustinGH** [comment]
My Ceton is using an assigned IP on my internal network, so I can get to the UI from any PC/device in the house.

I am trying from the same machine I run fHDHR.  Commenting out the bind just moves on to a badstatus line  error from r.begin()

I'll try to dig deeper later today.

**Comment by DanAustinGH** [comment]
I looked at another project and it uses an http call to tuner 6 status page:
http://192.167.200.1/Services/6/Status.html
If it gets a 404 response code it is a 4 tuner, otherwise a 6

**Comment by arrmo** [comment]
Nope, no 404 response here. I get a "hidden" page - that's why I tried the items below ... like Instance.css, and/or SSDP.

Thanks!

**Comment by DanAustinGH** [comment]
http://192.167.200.1/description.xml dumps a lot of details, but I do not see a tuner count.  You might see something in one of the  URLs listed for each device.  Failing that you could pull the log file (http://192.167.200.1/log.html) and look for "Proceeding with"

**Comment by arrmo** [comment]
Yep, the `description.xml` file hit me about the same time 😆. In the code I sent, just set `urlssdp` to http://192.167.200.1/description.xml ... and let the XML parsing happen from there. SSDP just gets that URL for you, that's really all it's doing.

**Comment by DanAustinGH** [comment]
Device Friendly Name:  Ceton InfiniTV Ethernet (00-80-8a-47) Tuner 1
Device Friendly Name:  Ceton InfiniTV Ethernet (00-80-8a-47) Tuner 2
Device Friendly Name:  Ceton InfiniTV Ethernet (00-80-8a-47) Tuner 3
Device Friendly Name:  Ceton InfiniTV Ethernet (00-80-8a-47) Tuner 4
Device Friendly Name:  Ceton InfiniTV Ethernet (00-80-8a-47) Tuner 5
Device Friendly Name:  Ceton InfiniTV Ethernet (00-80-8a-47) Tuner 6
Device Friendly Name:  Ceton InfiniTV (00-80-8a-47), OCTA 1
Device Friendly Name:  Ceton InfiniTV (00-80-8a-47), OCTA 2
Device Friendly Name:  Ceton InfiniTV (00-80-8a-47), OCTA 3

**Comment by arrmo** [comment]
Bingo! 😉. Yep, that's working - and SSDP isn't needed, unless you want to auto-detect the IP as well. That part sort of hit me after. Of course, auto-IP is kinda nice also.

BTW, I'll send you some more info a bit later, when I get to this, but ... that file contains links to "sub-data", that I believe lists out all the variables that can be queried. Likely some good info to be displayed (i.e. to the item about providing more info in the UI).

Thanks!

**Comment by arrmo** [comment]
OK, so from above - the tuner count is at that URL ... auto-detecting IP address or not 😄. I also modified my code a bit, pulled all the sub-items, more info below (sorry for the longer post!) ... OK, never mind - that's too long. So pasting the output here.

[discoveryDump.txt](https://github.com/fHDHR/fHDHR_plugin_origin_ceton/files/8028018/discoveryDump.txt)

But also, the output (XML) files - shows the available info / variables!
[ceton.zip](https://github.com/fHDHR/fHDHR_plugin_origin_ceton/files/8028024/ceton.zip)

**Comment by DanAustinGH** [comment]
I think I know why I am getting an empty Instance.css.  I suspect the device firmware only delivers a non-blank version for the 4 tuner cards.  So we can test to see if we get a response with content-length of zero for 6 tuner cards:
curl -v http://199.254.167.1/Instance.css 

Another possibility is to grab the system log and look for 'Proceeding with' -
curl -s http://199.254.167.1/log.html | grep 'Proceeding with'

**Comment by arrmo** [comment]
I like it! To the two you suggest, some output that may help,
1. curl -v http://199.254.167.1/Instance.css
```
< Content-Length: 86
.tab_Five { display: none; }
.tab_Six { display: none; }
.tab_Nine { display: none; }
```
2. curl -s http://199.254.167.1/log.html | grep 'Proceeding with' => I get no output?
3. Or, a third option ... curl -sI http://192.168.200.1/Instance.css | awk '/Content-Length/{print $2}'
```
86
```

Thoughts? I admit, I do like auto-detection 😄

**Comment by DanAustinGH** [comment]
It is possible the log rolls over and that string is not there.  I also see other log entries that suggest the count, containing the words instance or routing.

One thing about auto detecting, we have to be able to total count to the core, and I think it currently expects it to be set in the config.  I have to test that again, as I may have been having a different issue.  I think requiring the installer to set the device IP, device tuner count and total count should not be too much to handle, but I am open to automating what we can.

**Comment by DanAustinGH** [comment]
We can get the Content-Length using Python Requests, and if that value is greater than 0 we have a 4 tuner device.  We could be specific and say length of zero is a six tuner and a length of  86 is four, since I doubt we will get new firmware.

**Comment by arrmo** [comment]
Any thoughts on the best approach here? A few ideas above, just not sure which one to use?

Thanks!

**Comment by arrmo** [comment]
@DanAustinGH, any thoughts? Do we try to make this automatic, or just hard code in the config file?

Thanks!

**Comment by DanAustinGH** [comment]
I think adding support for multiple devices like we did earlier this year would make this more complicated than it is worth.  The config file already needs edited to add the device IP, so adding the count is hardly an obstacle.

**Comment by arrmo** [comment]
Makes sense, and no issue here. So just close this one out?

Thanks!

**Comment by DanAustinGH** [comment]
Agreed and closed.
