### ISSUE TITLE
Update Docs, To Note Ceton Firmware

### ISSUE THREAD

**Issue by arrmo** [fHDHR/fHDHR_plugin_origin_ceton#20]
Hi,

I admit, not sure if I should open this here, or in the plugin - but (thinking out loud here) ... should the docs "flow up" to top level, so they are all consolidated in one place? If so - include this here, and note about the needed Ceton firmware version? Also capture what version enables RTP, and also that the same firmware works for internal or external HW?

BTW, also - should a copy of the firmware be stored here somewhere, just in case (i.e. as a backup)?

Thanks!

**Comment by arrmo** [comment]
OK, this one I think still is needed - in particular the info about the firmware version, and RTP. Agreed?

@DanAustinGH, did you happen to confirm with your new card the exact version needed (minimum)?

Thanks!

**Comment by DanAustinGH** [comment]
We do need this, and it keeps getting bumped off my todo.  Also need to add notes about the multi device support.

As to minimum version, 13 and up are supposed to be good.  My new device came with 14.(something) and it worked fine before I upgraded to the latest.  I did not want to try downgrading to see where is broke...

**Comment by DanAustinGH** [comment]
I think adding a link to the firmware is OK.  Having a backup somewhere is likely a good idea.  Not sure that anyone would object to one of us hosting a copy (DCMA) since the company is long gone, but I am unclear about the github policy
