### ISSUE TITLE
Display Ceton Details in UI

### ISSUE THREAD

**Issue by arrmo** [fHDHR/fHDHR_plugin_origin_ceton#21]
Hi,

Like we discussed - display more Ceton info in the UI (firmware, etc.). Thinking this means changes at top level, and also in the plugin? Or do I have that wrong?

Thanks!

**Comment by arrmo** [comment]
Thinking this one is closed with my PR, agreed (@DanAustinGH)?

Thanks!

**Comment by DanAustinGH** [comment]
Sure!
